# Site/SEO settings
email: angel@contrerasangel.com
permalink: /:year/:month/:day/:title/
google_analytics: UA-125393232-1

title: Angel C's Blog
description: Simple Description
url: "https://angel-contreras.com"
baseurl: ""
twitter_username: angelfretz23
default_img: 

# Profile settings
name: Angel Contreras
profile_img: "/assets/img/profile-img.jpg"
profile: Born and raised in Southern California. I am a Software Engineer at Ticketmaster, an adaquet foosball player, and superb chess master. I like to think of myself as a taco to code converter.
social:
  github: https://github.com/angelfretz23
  instagram: https://www.instagram.com/angelc0123/
  linkedin-square: https://www.linkedin.com/in/angel-contreras/
    

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - .firebaserc
  - firebase.json

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed
